version: '3.9'
services:
  db:
    image: postgres:14.1
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=stellarCoffee
      - POSTGRES_PASSWORD=kopikopikopi
      - POSTGRES_DB=stellarCoffee
    volumes:
      - db_volume:/var/lib/postgresql/dta
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=noreply@stellarcoffee.com
      - PGADMIN_DEFAULT_PASSWORD=kopikopikopi
    depends_on:
      - db

volumes:
  db_volume: